<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Trupti_16" failures="1" tests="1" name="EdgeTest" time="28.767" errors="0" timestamp="2025-05-13T23:48:57 IST">
  <testcase classname="TestCases.TC_002_LoginTest" name="Verify_Login_Test" time="22.337">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at TestCases.TC_002_LoginTest.Verify_Login_Test(TC_002_LoginTest.java:43)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- Verify_Login_Test -->
</testsuite> <!-- EdgeTest -->
